# Generated by Django 5.1.3 on 2024-12-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jalan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jalan",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jalan",
            name="fclass",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="jalan",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="jalan",
            name="source",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="jalan",
            name="target",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
