# Generated by Django 5.1.3 on 2024-12-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jalan", "0002_alter_jalan_cost_alter_jalan_fclass_alter_jalan_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jalanmetadata",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
