# Generated by Django 5.1.3 on 2024-12-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jalan", "0008_alter_jalan_mline"),
    ]

    operations = [
        migrations.AddField(
            model_name="jalan",
            name="reverse_cost",
            field=models.DecimalField(
                blank=True, decimal_places=8, default=0, max_digits=15, null=True
            ),
        ),
    ]
