# Generated by Django 5.1.3 on 2024-11-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sekolah", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sekolah",
            name="nama",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
