# Generated by Django 5.1.3 on 2024-12-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectmetadata",
            old_name="layer",
            new_name="layers",
        ),
    ]
