# Generated by Django 5.1.1 on 2024-11-11 21:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BatasWilayahMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tb_batas_wilayah_metadata",
            },
        ),
        migrations.CreateModel(
            name="BatasWilayah",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("properties", models.JSONField()),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batas_wilayah",
                        to="batas_wilayah.bataswilayahmetadata",
                    ),
                ),
            ],
            options={
                "db_table": "tb_batas_wilayah",
            },
        ),
    ]
