# Generated by Django 5.1.3 on 2024-11-13 13:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batas_wilayah", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bataswilayahmetadata",
            name="bbox",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
